version: 2
updates:
  - package-ecosystem: "bundler"
    directories:
      - "/"
      - "gemfiles/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
