require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/*

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/*_helper.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false