require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/*_helper.rb

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Metrics/AbcSize:
  Enabled: false
  
Metrics/BlockLength:
  AllowedMethods:
    - class_methods

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'method_call']
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  CountAsOne: ['array', 'heredoc', 'method_call']
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5