name: Generate CHANGELOG.md

on:
  workflow_run: # workflow_run only runs on default branch
    workflows: [publish]
    types: [completed]
    branches: [main] # prevent test runs in other branches trigger change log generation in main branch
  workflow_dispatch: # allow manual run of workflow
  schedule:
    - cron: 0 12 * * 5

concurrency:
  group: generate-changelog
  cancel-in-progress: true

jobs:
  changelog_generator:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    timeout-minutes: 3
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate CHANGELOG.md
        env:
          CHANGELOG_GITHUB_TOKEN: ${{ github.token }}
        run: |
          bundle exec rake changelog

      - name: Commit CHANGELOG.md
        uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: |
            CHANGELOG.md
          commit-message: "ci: update CHANGELOG.md"
