name: publish

on:
  push:
    branches: [main]
    paths: ["lib/mime_actor/version.rb"]

jobs:
  rubygems:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      id-token: write

    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Rspec
        run: |
          bundle exec rake spec

      - name: Checkout new Release branch
        run: |
          git checkout -b release

      - name: Release New Version
        uses: rubygems/release-gem@v1
        with:
          await-release: false

      - name: Clean up Release branch
        if: always()
        run: |
          git ls-remote --exit-code --heads origin refs/heads/release && echo "release branch existed in remote" && git push -d origin refs/heads/release

