name: Release New Version

on:
  workflow_run: # only runs on default branch
    workflows: [CI]
    types: [completed]
    branches: [main]
    paths: ["lib/mime_actor/version.rb"]

jobs:
  rubygems:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      id-token: write
    environment: release
    timeout-minutes: 3
    
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
          bundler-cache: true

      - run: bundle exec rake spec

      - uses: ryancyq/bundle-release-gem@v1
